frappe.pages["velara-about"].on_page_load = function(wrapper) {
    const page = frappe.ui.make_app_page({ parent: wrapper, title: __("About Velara"), single_column: true });
    $(page.body).html('<div id="velara_about-root"></div>');
    _render_velara_about(page);
};
function _render_velara_about(page) {
    const B = "#8B5CF6", BL = "#EDE9FE", BD = "#5B21B6";
    const slides = [
        { title: __("What is Velara?"), icon: "bed", content: `<div class="ab-card"><div class="ab-hero"><svg viewBox="0 0 120 120" width="100" height="100"><circle cx="60" cy="60" r="55" fill="${BL}" stroke="${B}" stroke-width="3"><animate attributeName="r" values="52;55;52" dur="3s" repeatCount="indefinite"/></circle><text x="60" y="68" text-anchor="middle" font-size="36" fill="${BD}" font-weight="bold">🏨</text></svg></div><h3>${__("Velara")}</h3><p>${__("Comprehensive Hospitality Management")}</p><div class="ab-chips"><div class="ab-chip"><span>🏨</span> ${__("Reservations")}</div>\n<div class="ab-chip"><span>🏨</span> ${__("Front Desk")}</div>\n<div class="ab-chip"><span>🏨</span> ${__("Housekeeping")}</div>\n<div class="ab-chip"><span>🏨</span> ${__("F&B")}</div>\n<div class="ab-chip"><span>🏨</span> ${__("Revenue Management")}</div>\n<div class="ab-chip"><span>🏨</span> ${__("Guest Services")}</div>\n<div class="ab-chip"><span>🏨</span> ${__("Events")}</div>\n<div class="ab-chip"><span>🏨</span> ${__("Maintenance")}</div>\n<div class="ab-chip"><span>🏨</span> ${__("Loyalty")}</div>\n<div class="ab-chip"><span>🏨</span> ${__("Spa")}</div>\n<div class="ab-chip"><span>🏨</span> ${__("Night Audit")}</div></div></div>` },
        { title: __("Module Map"), icon: "sitemap", content: `<div class="ab-card"><p class="text-muted mb-3">${__("Interactive map of all modules.")}</p><div id="ab-appmap" style="min-height:420px;border:1px solid var(--border-color);border-radius:12px"></div></div>`, onShow() { if(frappe.visual&&frappe.visual.appMap) frappe.visual.appMap({container:"#ab-appmap",app:"velara",interactive:true}); else $("#ab-appmap").html('<p class="text-muted text-center p-5">'+__("Install frappe_visual.")+"</p>"); } },
        { title: __("Entity Relationships"), icon: "hierarchy-3", content: `<div class="ab-card"><div id="ab-erd" style="min-height:420px;border:1px solid var(--border-color);border-radius:12px"></div></div>`, onShow() { if(frappe.visual&&frappe.visual.RelationshipExplorer) frappe.visual.RelationshipExplorer.create({container:"#ab-erd",app:"velara"}); else $("#ab-erd").html('<p class="text-muted text-center p-5">'+__("Install frappe_visual.")+"</p>"); } },
        { title: __("Integration Map"), icon: "plug-connected", content: `<div class="ab-card"><h3>${__("How Velara Connects")}</h3><p>${__("Integrates with ERPNext, HRMS, CAPS, Frappe Visual, and Arkan Help.")}</p><div class="ab-grid"><div class="ab-int">🔗 ERPNext</div><div class="ab-int">👥 HRMS</div><div class="ab-int">🛡️ CAPS</div><div class="ab-int">👁️ Visual</div><div class="ab-int">❓ Help</div></div></div>` },
        { title: __("Security & Permissions"), icon: "shield-check", content: `<div class="ab-card"><h3>${__("CAPS-Integrated Security")}</h3><p>${__("Fine-grained capability-based access control.")}</p><div class="ab-chips"><div class="ab-chip">🔑 ${__("Capabilities")}</div><div class="ab-chip">🔒 ${__("Field Masking")}</div><div class="ab-chip">⚡ ${__("Action Gates")}</div><div class="ab-chip">📋 ${__("Policies")}</div></div></div>` },
        { title: __("Getting Started"), icon: "rocket", content: `<div class="ab-card"><h3>${__("Quick Start")}</h3><p>${__("Follow the onboarding wizard for a guided tour.")}</p><div style="text-align:center;margin-top:20px"><button class="btn btn-primary btn-lg" onclick="frappe.set_route('velara-onboarding')">${__("Start Onboarding")}</button></div></div>` },
    ];
    if(frappe.visual&&frappe.visual.Storyboard) { frappe.visual.Storyboard.create({container:page.body,slides,brand_color:B,navigation:"both"}); }
    else { let h='<div style="max-width:900px;margin:0 auto;padding:20px">'; slides.forEach((s,i)=>{h+=`<div style="margin-bottom:24px;padding:20px;border:1px solid var(--border-color);border-radius:12px"><h2 style="color:${B}">${s.title}</h2>${s.content}</div>`}); h+="</div>"; $(page.body).find("#velara_about-root").html(h); setTimeout(()=>slides.forEach(s=>{if(s.onShow)s.onShow()}),300); }
}
frappe.dom.set_style(`.ab-card{padding:24px;text-align:center}.ab-hero{margin-bottom:16px}.ab-chips{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;margin-top:16px}.ab-chip{display:inline-flex;align-items:center;gap:6px;padding:6px 14px;border-radius:20px;background:var(--bg-light-gray,#f5f5f5);font-size:13px;border:1px solid var(--border-color)}.ab-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:12px;margin-top:16px}.ab-int{padding:12px;border-radius:8px;background:var(--bg-light-gray,#f5f5f5);text-align:center;border:1px solid var(--border-color)}`);
